base = '/'
publish = 'dist/'
command = 'npm run build'

[dev]
  framework = 'vite'
  targetPort = 5173
  command = 'npm run dev'

[functions."word"]
  schedule = "28 16 * * *"

[functions."picture"]
  schedule = "28 16 * * *"